### ISSUE TITLE
Missing red guideline on capture screen

### ISSUE THREAD

**Issue by jaguarg** [Mole93/plugin-barcode-ios#2]
When scanning, we can see the green area box, but the red guide line is missing.
The attached screenshot shows what was expected.
![screen shot 2016-12-03 at 22 18 51](https://cloud.githubusercontent.com/assets/8936602/20862345/4439ec14-b9a8-11e6-9c05-0f2ea14616f7.png)

**Comment by donini-tech** [comment]
I fixed it. You can download the code from github or you can update the plugin

**Comment by jaguarg** [comment]
Great thanks. Works perfectly !

**Comment by jaguarg** [comment]
Hi @Mole93, I just tried upload my app to itunes connect, and I get this warning email. 

Does the plugin require this? 

_This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data._

**Comment by donini-tech** [comment]
Hi @jaguarg, my plugin doesn't use NSPhotoLibraryUsageDescription but it uses NSCameraUsageDescription. The NSPhotoLibraryUsageDescription is a feature to access to PhotoLibrary so I think that some other plugin uses it. Anyway, to fix it you need to go to your info.plist file and to add  ` Privacy - Photo Library Usage Description` and as a value, you need to add `To take a picture`
